// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjHG9SAiDeN6lOLqm4xuOZiEMmKb5d5_Q',
    appId: '1:794347808656:android:4aab337326522a704ef515',
    messagingSenderId: '794347808656',
    projectId: 'terra-app-372401',
    databaseURL: 'https://terra-app-372401-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'terra-app-372401.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ6u6y9V53LRCEbKjp7xTL9tOPEo14-MQ',
    appId: '1:794347808656:ios:941f3eb41ec8904e4ef515',
    messagingSenderId: '794347808656',
    projectId: 'terra-app-372401',
    databaseURL: 'https://terra-app-372401-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'terra-app-372401.appspot.com',
    androidClientId: '794347808656-5oug52p8bv5s25l2r6k6p9k4kmmcgg3j.apps.googleusercontent.com',
    iosClientId: '794347808656-i9jdk1t76j26ra5hmdp9qmrekfrq0hqd.apps.googleusercontent.com',
    iosBundleId: 'ph.terraapp.terra',
  );

}