final List<String> categoryList = [
  "Cleaning",
  "Laundry",
  "Car Repair",
  "Electrician",
  "Gardener",
  "AC Repair",
  "Photographer",
  "Driver",
  "Medicine",
  "Delivery",
  "Housekeeper",
  "Private Tutor",
  "Car Wash",
  "Carpenter",
  "Personal Assistant",
  "Food Delivery",
  "Make-up Artist",
  "Plumber",
  "Computer Repair",
  "Motorcycle Repair",
  "Groceries",
  "Others",
];
